version: "3.7"
services:
  mongo:
    image: mongo
    volumes:
     - ./mongo:/data/db
    entrypoint: ["/usr/bin/mongod", "--auth", "--dbpath", "/data/db", "--bind_ip", "localhost,tourneydb_mongo_1", "--replSet", "rs0"]
#    entrypoint: ["/usr/bin/mongod", "--dbpath", "/data/db", "--bind_ip", "localhost,tourneydb_mongo_1", "--replSet", "rs0"]
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "24420:24420"
  admin:
    build: ./admin
    volumes:
      - ./admin:/usr/src/app
  www:
    build: ./www
    volumes:
      - ./www:/usr/src/app
